name: Deploy React App and Node.js Backend

on:
  push:
    branches:
      - main

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install Frontend Dependencies
        working-directory: frontend/hirekar
        run: npm install

      - name: Build Frontend Project
        working-directory: frontend/hirekar
        run: npm run build

      - name: Deploy Frontend to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
        run: |
          aws s3 sync frontend/hirekar/dist/ s3://$S3_BUCKET_NAME --delete

  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-frontend

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 16.171.195.37 >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          DB_USERNAME: ${{ secrets.DB_USERNAME }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          GEOCODE_API_KEY: ${{ secrets.GEOCODE_API_KEY }}
        run: |
          ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/hirekar-mern/backend
            git pull origin main
            npm install
            pm2 restart all
          EOF
